# Generated by Django 5.1.3 on 2024-11-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='owner',
            new_name='user',
        ),
    ]
