# Generated by Django 5.1.3 on 2024-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0002_rename_owner_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='upload_data',
            field=models.FileField(blank=True, null=True, upload_to='lesson_media'),
        ),
    ]
