# Generated by Django 5.1.3 on 2024-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0003_lesson_name_lesson_upload_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
