# Generated by Django 5.1.3 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0006_lesson_date_to_answer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
