# Generated by Django 5.1.3 on 2024-12-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0008_lesson_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
