# Generated by Django 5.1.3 on 2024-12-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0011_lesson_max_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='max_mark',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
