# Generated by Django 5.1.4 on 2025-01-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0012_alter_lesson_max_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_send',
            field=models.BooleanField(default=False),
        ),
    ]
